import React from "react";
import MainHome from "./Components/Home/MainHome";

// SEO metadata for the homepage with 100+ keywords
export const metadata = {
  title: "Home - Nexo Mark | Expert Web Development & Digital Marketing",
  description:
    "Nexo Mark helps businesses grow through expert web development, SEO, digital marketing, branding, video editing, and stunning design. Build your brand with purpose-driven solutions that deliver results.",
  keywords: [
    "web development",
    "SEO",
    "digital marketing",
    "branding",
    "video editing",
    "Nexo Mark",
    "business growth",
    "stunning design",
    "custom websites",
    "performance marketing",
    "website design",
    "responsive websites",
    "UI/UX design",
    "graphic design",
    "eCommerce websites",
    "SEO services",
    "content marketing",
    "PPC marketing",
    "social media marketing",
    "search engine optimization",
    "web design services",
    "web development agency",
    "branding solutions",
    "logo design",
    "brand strategy",
    "brand identity",
    "digital branding",
    "custom branding",
    "website development",
    "mobile website design",
    "SEO for businesses",
    "digital marketing agency",
    "business websites",
    "startup websites",
    "lead generation",
    "local SEO",
    "global SEO",
    "website SEO",
    "SEO audit",
    "Google SEO",
    "SEO content",
    "online marketing",
    "digital transformation",
    "market research",
    "social media advertising",
    "paid ads",
    "Instagram marketing",
    "Facebook ads",
    "YouTube marketing",
    "LinkedIn marketing",
    "eCommerce marketing",
    "PPC campaigns",
    "Google Ads",
    "Google analytics",
    "SEO consulting",
    "conversion optimization",
    "conversion rate optimization",
    "web applications",
    "website redesign",
    "website performance",
    "website speed optimization",
    "user experience",
    "customer engagement",
    "video production",
    "corporate branding",
    "product branding",
    "website maintenance",
    "CMS development",
    "WordPress development",
    "Next.js development",
    "React development",
    "Vue.js development",
    "Node.js development",
    "custom web applications",
    "cloud hosting",
    "website hosting",
    "secure websites",
    "website security",
    "content strategy",
    "branding design",
    "email marketing",
    "inbound marketing",
    "sales funnel",
    "online presence",
    "digital solutions",
    "content creation",
    "UX/UI design",
    "web development services",
    "custom themes",
    "user interface design",
    "website wireframes",
    "website prototyping",
    "website analytics",
    "website accessibility",
    "mobile apps",
    "business growth strategies",
    "online branding",
    "social media content",
    "web analytics",
    "eCommerce design",
    "affiliate marketing",
    "online advertising",
    "search engine marketing",
    "SEO link building",
    "backlinking",
    "content marketing strategy",
    "digital media",
    "social media campaigns",
    "graphic design services",
    "SEO expert",
    "web design trends",
    "conversion tracking",
    "SEO tools",
    "web development company",
    "enterprise web development",
    "B2B digital marketing",
    "B2C marketing",
    "digital marketing strategy",
    "website conversion",
    "web branding",
    "digital brand identity",
    "local business SEO",
    "SEO website audit",
    "SEO copywriting",
  ],
  openGraph: {
    title: "Nexo Mark - Grow Your Business with Digital Expertise",
    description:
      "Explore Nexo Mark's comprehensive services designed to help your business thrive in the digital age. From web development to marketing, we provide custom solutions tailored to your brand's success.",
    url: "https://www.nexomark.agency",
    type: "website",
    siteName: "Nexo Mark",
  },
  alternates: {
    canonical: "https://www.nexomark.agency",
  },
  other: {
    "instagram:creator": "@nexomark.agency",
    "linkedin:company": "nexo-mark",
    "fb:profile_id": "61575301816998",
    "og:social_links": JSON.stringify([
      {
        platform: "linkedin",
        url: "https://www.linkedin.com/company/nexo-mark",
      },
      {
        platform: "instagram",
        url: "https://www.instagram.com/nexomark.agency/",
      },
      {
        platform: "facebook",
        url: "https://www.facebook.com/profile.php?id=61575301816998",
      },
    ]),
  },
};

const Home = () => {
  return (
    <main>
      <MainHome />
    </main>
  );
};

export default Home;
